[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
lib_deps =
    u8g2
    bblanchon/ArduinoJson
    bxparks/AceButton
    me-no-dev/ESPAsyncWebServer
    me-no-dev/AsyncTCP
    jgromes/RadioLib
lib_ldf_mode = deep
extra_scripts = pre:embed_html.py
build_flags =
    -DASYNCWEBSERVER_REGEX
    -DMESHTEXT_VERSION=\"dev\"
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = default_8MB.csv
