[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
lib_deps =
    u8g2
    bblanchon/ArduinoJson
    bxparks/AceButton
monitor_speed = 115200
board_build.filesystem = littlefs
; Phase 3 adds: me-no-dev/ESPAsyncWebServer, me-no-dev/AsyncTCP
; Phase 4 adds: jgromes/RadioLib
